app:
    resource: "@AppBundle/Controller/"
    type:     annotation
blog_show:
    path:      /blog/{slug}
    defaults:  { _controller: AppBundle:Blog:show }
logout:
    path: /logout
# forgot:
#     path: /forgot
#     defaults:  {_controller: AppBundle:ForgotPassword:forgotPassword}
