# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User: 
  fields: 
    email: 
      length: 255
      type: string
    password: 
      length: 64
      type: string
    username: 
      length: 255
      type: string
    isActive:
      type:boolean
  id: 
    id: 
        type: integer
        generator: { strategy: AUTO }
  table: user
  type: entity